service: eagle

plugins:
  - serverless-appsync-plugin
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage}
  region: eu-west-1
  environment:
    STAGE: ${opt:stage}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:putObject"
      Resource:
        - arn:aws:s3:::eagle-file-system-${opt:stage}/*

# LAMBDAs
functions:
  getBlogs:
    handler: handlers/get-blogs.handler
  
  create:
    handler: handlers/create.handler

custom:
  accountId:
    Ref: AWS::AccountId

  appSync:
    name: eage-${opt:stage}-api
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      awsRegion: eu-west-1
      defaultAction: ALLOW
      userPoolId:  { Ref: CognitoUserPool } 

    mappingTemplates: ${file(graph-ql/mapping-templates/mapping-templates.yml)}
    mappingTemplatesLocation: graph-ql/mapping-templates
    
    schema: ./graph-ql/schema/schema.graphql
    
    dataSources: ${file(graph-ql/datasources/datasources.yml)}

    serviceRole: "AppSyncServiceRole"

# you can add CloudFormation resource templates here
resources:
 Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: blog-user-pool

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: blog-client
      UserPoolId:
        Ref: CognitoUserPool

  CognitoIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: blog_identity_pool
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId:
            Ref: CognitoUserPoolClient
          ProviderName:
            Fn::GetAtt: [CognitoUserPool, ProviderName]

    # Roles (IAM) - defines what services you have access to

  CognitoIdentityPoolRoles:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId:
        Ref: CognitoIdentityPool
      Roles:
        authenticated:
          Fn::GetAtt: [CognitoAuthRole, Arn]
        unauthenticated:
          Fn::GetAtt: [CognitoUnauthRole, Arn]
      
  CognitoAuthRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: blog-auth-role
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Federated: "cognito-identity.amazonaws.com"
            Action:
            - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                  "cognito-identity.amazonaws.com:amr": authenticated
      Policies:
        - PolicyName: "CognitoAuthorizedPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "mobileanalytics:PutEvents"
                  - "cognito-sync:*"
                  - "cognito-identity:*"
                Resource: "*"
              - Effect: "Allow"
                Action: 
                  - "execute-api:Invoke"
                Resource: "*"
              
  CognitoUnauthRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: blog-unauth-role
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Federated: "cognito-identity.amazonaws.com"
            Action:
            - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                  "cognito-identity.amazonaws.com:amr": authenticated
      Policies:
        - PolicyName: "CognitoAuthorizedPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "mobileanalytics:PutEvents"
                  - "cognito-sync:*"
                  - "cognito-identity:*"
                Resource: "*"

  AppSyncLambdaServiceRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: "Lambda-${self:custom.appSync.serviceRole}"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "appsync.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Policies:
          - PolicyName: "Lambda-${self:custom.appSync.serviceRole}-Policy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "lambda:invokeFunction"
                  Resource:
                    - "*"
              
  EagleFileBucket: 
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: eagle-file-system-${opt:stage}
      